export const docInfo = {
  name: "GPQ Default Module",
  version: "1.0",
  title: "",
  description: "USER-DEFINED DESCRIPTION",
  items: "120",
  elmRoles: "AC AD AT CB CL CM CR CT NT OR PL PS SA SC SD ST",
	intro: "HTML Contents",
}

export const firstElms = [
  ["CT","Membuat kesimpulan dari beragam situasi."],
  ["AT","Menganalisa beragam hal sampai detail."],
  ["CR","Mendiskusikan ide-ide baru."],
  ["PL","Menyiapkan rencana detail termasuk resiko kegagalannya."],
  ["CL","Memastikan tidak ada penyimpangan dalam pekerjaan."],
  ["CB","Saling bantu membantu dalam kelompok kerja."],
  ["CM","Menyampaikan ide baru di hadapan kelompok kerja."],
  ["SC","Menahan diri untuk tidak terbawa emosi."],
  ["ST","Memproyeksikan keadaan sekarang ke masa depan."],
  ["CT","Menelaah hal-hal yang bersifat konseptual."],
  ["AT","Mendalami suatu topik serinci mungkin."],
  ["CR","Mengembangkan metode baru dalam rangka efisiensi kerja."],
  ["PL","Merencanakan langkah kerja sesuai dengan waktu dan sumberdaya."],
  ["CL","Mengawasi kesesuaian pelaksanaan dengan rencana kerja."],
  ["CB","Mendorong orang agar mampu berkontribusi maksimal di tim kerjanya."],
  ["CM","Menyampaikan pendapat ke kelompok kerja yang baru."],
  ["OR","Mengorganisir pelaksanaan beragam proyek supaya tidak tumpang tindih."],
  ["ST","Mengantisipasi kendala yang akan muncul di masa mendatang."],
  ["CT","Menyimpulkan hasil sebuah proses diskusi."],
  ["AT","Mengerjakan hal-hal detail."],
  ["CR","Mempraktekkan cara yang baru pada pekerjaan yang rutin."],
  ["PL","Mengembangkan target kerja menjadi langkah kerja yang rinci."],
  ["CL","Mengevaluasi pelaksanaan setiap rencana kerja."],
  ["CB","Membangun terciptanya semangat kerjasama pada suatu tim."],
  ["SA","Mengenali kondisi emosi orang lain."],
  ["OR","Memastikan kesesuaian alokasi sumberdaya dengan prioritas kerja."],
  ["ST","Membuat simulasi jangka panjang."],
  ["CT","Mengenalkan wacana baru untuk suatu kegiatan yang rutin."],
  ["AT","Mengurai masalah hingga ke akar permasalahan."],
  ["CR","Mengembangkan pendekatan baru untuk hal yang sudah rutin."],
  ["PL","Merencanakan pekerjaaan secara teratur dan rapi dalam situasi apapun."],
  ["CL","Mengidentifikasi penyimpangan yang terjadi pada pekerjaan."],
  ["NT","Membina dan mengembangkan hubungan yang saling menguntungkan."],
  ["SA","Memperhatikan pengaruh emosi pada kinerja."],
  ["OR","Mengarahkan sumber daya untuk mencapai target."],
  ["ST","Menganalisa kemungkinan yang bisa terjadi di masa depan."],
  ["CT","Membandingkan teori dengan kenyataan."],
  ["AT","Menganalisa situasi hingga akar permasalahan."],
  ["CR","Melakukan pekerjaan yang sama dengan cara yang berbeda."],
  ["PL","Memilah tujuan menjadi langkah-langkah kerja."],
  ["PS","Membuat orang lain mendukung pendapat pribadi yang disampaikan."],
  ["NT","Membangun jaringan kerja dengan beragam pihak."],
  ["SA","Mencermati kondisi emosi orang lain."],
  ["OR","Mengelola kelebihan dan kekurangan sumberdaya saat bekerja."],
  ["ST","Mendiskusikan strategi jangka panjang."],
  ["CT","Membuat kesimpulan dari beragam informasi."],
  ["AT","Menganalisa beragam hal sampai detail."],
  ["CR","Mendiskusikan ide-ide baru."],
  ["AD","Mencari cara terbaik menghadapi perubahan."],
  ["PS","Membuat orang lain mau menerima gagasan pribadi."],
  ["NT","Membangun kedekatan dan keakraban kelompok kerja."],
  ["SA","Memahami sudut pandang orang lain."],
  ["OR","Memastikan sumberdaya teralokasi secara efektif dan efisien."],
  ["ST","Memproyeksikan keadaan sekarang ke masa depan."],
  ["CT","Menelaah hal-hal yang bersifat konseptual."],
  ["AT","Mendalami suatu topik serinci mungkin."],
  ["SD","Menindaklanjuti umpan balik mengenai diri saya."],
  ["AD","Menyesuaikan diri dengan beragam hal di lingkungan baru."],
  ["PS","Mempengaruhi orang lain untuk menerima pendapat pribadi."],
  ["NT","Mengembangkan jejaring/hubungan sosial seluas mungkin."],
  ["SA","Menangkap situasi emosi orang lain."],
  ["OR","Mengorganisir pelaksanaan beragam proyek supaya tidak tumpang tindih."],
  ["ST","Mengantisipasi kendala yang akan muncul di masa mendatang."],
  ["CT","Menyimpulkan hasil sebuah proses diskusi."],
  ["SC","Tetap tenang dalam menghadapi tekanan emosi."],
  ["SD","Meningkatkan kemampuan diri secara berkesinambungan."],
  ["AD","Menyesuaikan perilaku dengan tuntutan perubahan."],
  ["PS","Bernegosiasi dalam rangka pendapat pribadi dapat diterima."],
  ["NT","Memupuk dan mengelola jejaring/hubungan sosial yang erat."],
  ["SA","Mengenali kondisi emosi orang lain."],
  ["OR","Memastikan kesesuaian alokasi sumberdaya dengan prioritas kerja."],
  ["ST","Membuat simulasi jangka panjang."],
  ["CM","Saya mudah mengekspresikan gagasan."],
  ["SC","Mudah bangkit dari kekecewaan."],
  ["SD","Mencari cara-cara pengembangan diri yang efektif."],
  ["AD","Mencermati perubahan dan menelaah kendala-kendalanya."],
  ["PS","Memakai beragam pendekatan supaya pendapat pribadi diterima."],
  ["NT","Membina dan mengembangkan hubungan yang saling menguntungkan."],
  ["SA","Memperhatikan pengaruh emosi pada kinerja."],
  ["OR","Mengarahkan sumber daya untuk mencapai target."],
  ["CB","Saling bantu membantu dalam kelompok kerja."],
  ["CM","Menyampaikan ide baru di hadapan kelompok kerja."],
  ["SC","Menahan diri untuk tidak terbawa emosi."],
  ["SD","Melakukan beragam kegiatan untuk mengatasi kekurangan diri."],
  ["AD","Menyesuaikan pola kerja sesuai dengan kondisi yang berubah-ubah"],
  ["PS","Membuat orang lain mendukung pendapat pribadi yang disampaikan."],
  ["NT","Membangun jaringan kerja dengan beragam pihak."],
  ["SA","Mencermati kondisi emosi orang lain."],
  ["CL","Mengawasi kesesuaian pelaksanaan dengan rencana kerja."],
  ["CB","Mendorong orang agar mampu berkontribusi maksimal di tim kerjanya."],
  ["CM","Menyampaikan pendapat ke kelompok kerja yang baru."],
  ["SC","Tetap tenang di saat-saat yang menegangkan."],
  ["SD","Mencari kesempatan untuk mengembangkan diri."],
  ["AD","Mencari cara terbaik menghadapi perubahan."],
  ["PS","Membuat orang lain mau menerima gagasan pribadi."],
  ["NT","Membangun kedekatan dan keakraban kelompok kerja."],
  ["PL","Mengembangkan target kerja menjadi langkah kerja yang rinci."],
  ["CL","Mengevaluasi pelaksanaan setiap rencana kerja."],
  ["CB","Membangun terciptanya semangat kerjasama pada suatu tim."],
  ["CM","Menyampaikan pendapat secara terbuka."],
  ["SC","Tetap berpikir jernih ketika berada di bawah tekanan."],
  ["SD","Menindaklanjuti umpan balik mengenai diri saya."],
  ["AD","Menyesuaikan diri dengan beragam hal di lingkungan baru."],
  ["PS","Mempengaruhi orang lain untuk menerima pendapat pribadi."],
  ["CR","Mengembangkan pendekatan baru untuk hal yang sudah rutin."],
  ["PL","Merencanakan pekerjaaan secara teratur dan rapi dalam situasi apapun."],
  ["CL","Mengidentifikasi penyimpangan yang terjadi pada pekerjaan."],
  ["CB","Berpartisipasi dalam kegiatan kelompok."],
  ["CM","Bertukar pikiran secara terbuka dengan orang lain."],
  ["SC","Tetap tenang dalam menghadapi tekanan emosi."],
  ["SD","Meningkatkan kemampuan diri secara berkesinambungan."],
  ["AD","Menyesuaikan perilaku dengan tuntutan perubahan."],
  ["AT","Menganalisa situasi hingga akar permasalahan."],
  ["CR","Melakukan pekerjaan yang sama dengan cara yang berbeda."],
  ["PL","Memilah tujuan menjadi langkah-langkah kerja."],
  ["CL","Memantau kesalahan pelaksanaan pekerjaan."],
  ["CB","Berkomitmen untuk mendukung keputusan kelompok."],
  ["CM","Mudah mengekspresikan gagasan."],
  ["SC","Mudah bangkit dari kekecewaan."],
  ["SD","Mencari cara-cara pengembangan diri yang efektif."],
  // [null, null] // HACK
]

export const secondElms = [
  ["ST","Mendiskusikan strategi jangka panjang."],
  ["OR","Mengelola kelebihan dan kekurangan sumberdaya saat bekerja."],
  ["SA","Mencermati kondisi emosi orang lain."],
  ["NT","Membangun jaringan kerja dengan beragam pihak."],
  ["PS","Membuat orang lain mendukung pendapat pribadi yang disampaikan."],
  ["AD","Menyesuaikan pola kerja sesuai dengan kondisi yang berubah-ubah."],
  ["SD","Melakukan beragam kegiatan untuk mengatasi kekurangan diri."],
  ["AC","Bekerja dalam suasana yang kompetitif."],
  ["OR","Memastikan sumberdaya teralokasi secara efektif dan efisien."],
  ["SA","Memahami sudut pandang orang lain."],
  ["NT","Membangun kedekatan dan keakraban kelompok kerja."],
  ["PS","Membuat orang lain mau menerima gagasan pribadi."],
  ["AD","Mencari cara terbaik menghadapi perubahan."],
  ["SD","Mencari kesempatan untuk mengembangkan diri."],
  ["SC","Tetap tenang di saat-saat yang menegangkan."],
  ["AC","Memiliki dorongan kuat untuk mencapai tujuan"],
  ["SA","Menangkap situasi emosi orang lain."],
  ["NT","Mengembangkan jejaring/hubungan sosial seluas mungkin."],
  ["PS","Mempengaruhi orang lain untuk menerima pendapat pribadi."],
  ["AD","Menyesuaikan diri dengan beragam hal di lingkungan baru."],
  ["SD","Menindaklanjuti umpan balik mengenai diri saya."],
  ["SC","Tetap berpikir jernih ketika berada di bawah tekanan."],
  ["CM","Menyampaikan pendapat secara terbuka."],
  ["AC","Menetapkan sasaran yang menantang."],
  ["NT","Memupuk dan mengelola jejaring/hubungan sosial yang erat."],
  ["PS","Bernegosiasi dalam rangka pendapat pribadi dapat diterima."],
  ["AD","Menyesuaikan perilaku dengan tuntutan perubahan."],
  ["SD","Meningkatkan kemampuan diri secara berkesinambungan."],
  ["SC","Tetap tenang dalam menghadapi tekanan emosi."],
  ["CM","Bertukar pikiran secara terbuka dengan orang lain."],
  ["CB","Berpartisipasi dalam kegiatan kelompok."],
  ["AC","Bersemangat menghadapi pekerjaan yang menantang."],
  ["PS","Memakai beragam pendekatan supaya pendapat pribadi diterima."],
  ["AD","Mencermati perubahan dan menelaah kendala-kendalanya."],
  ["SD","Mencari cara-cara pengembangan diri yang efektif."],
  ["SC","Mudah bangkit dari kekecewaan."],
  ["CM","Saya mudah mengekspresikan gagasan."],
  ["CB","Berkomitmen untuk mendukung keputusan kelompok."],
  ["CL","Memantau kesalahan pelaksanaan pekerjaan."],
  ["AC","Mengerjakan segala sesuatunya lebih baik dari yang lain."],
  ["AD","Menyesuaikan pola kerja sesuai dengan kondisi yang berubah-ubah."],
  ["SD","Melakukan beragam kegiatan untuk mengatasi kekurangan diri."],
  ["SC","Menahan diri untuk tidak terbawa emosi"],
  ["CM","Menyampaikan ide baru di hadapan kelompok kerja."],
  ["CB","Saling bantu membantu dalam kelompok kerja."],
  ["CL","Memastikan tidak ada penyimpangan dalam pekerjaan."],
  ["PL","Menyiapkan rencana detail termasuk resiko kegagalannya."],
  ["AC","Bekerja dalam suasana yang kompetitif."],
  ["SD","Mencari kesempatan untuk mengembangkan diri."],
  ["SC","Tetap tenang di saat-saat yang menegangkan."],
  ["CM","Menyampaikan pendapat ke kelompok kerja yang baru."],
  ["CB","Mendorong orang agar mampu berkontribusi maksimal di tim kerjanya."],
  ["CL","Mengawasi kesesuaian pelaksanaan dengan rencana kerja."],
  ["PL","Merencanakan langkah kerja sesuai dengan waktu dan sumberdaya."],
  ["CR","Mengembangkan metode baru dalam rangka efisiensi kerja."],
  ["AC","Memiliki dorongan kuat untuk mencapai tujuan."],
  ["SC","Tetap berpikir jernih ketika berada di bawah tekanan."],
  ["CM","Menyampaikan pendapat secara terbuka."],
  ["CB","Membangun terciptanya semangat kerjasama pada suatu tim."],
  ["CL","Mengevaluasi pelaksanaan setiap rencana kerja."],
  ["PL","Mengembangkan target kerja menjadi langkah kerja yang rinci."],
  ["CR","Mempraktekkan cara yang baru pada pekerjaan yang rutin."],
  ["AT","Mengerjakan hal-hal detail."],
  ["AC","Menetapkan sasaran yang menantang."],
  ["CM","Bertukar pikiran secara terbuka dengan orang lain."],
  ["CB","Berpartisipasi dalam kegiatan kelompok."],
  ["CL","Mengidentifikasi penyimpangan yang terjadi pada pekerjaan."],
  ["PL","Merencanakan pekerjaaan secara teratur dan rapi dalam situasi apapun."],
  ["CR","Mengembangkan pendekatan baru untuk hal yang sudah rutin."],
  ["AT","Mengurai masalah hingga ke akar permasalahan."],
  ["CT","Mengenalkan wacana baru untuk suatu kegiatan yang rutin."],
  ["AC","Bersemangat menghadapi pekerjaan yang menantang."],
  ["CB","Berkomitmen untuk mendukung keputusan kelompok."],
  ["CL","Memantau kesalahan pelaksanaan pekerjaan."],
  ["PL","Memilah tujuan menjadi langkah-langkah kerja."],
  ["CR","Melakukan pekerjaan yang sama dengan cara yang berbeda."],
  ["AT","Menganalisa situasi hingga akar permasalahan."],
  ["CT","Membandingkan teori dengan kenyataan."],
  ["ST","Menganalisa kemungkinan yang bisa terjadi di masa depan."],
  ["AC","Mengerjakan segala sesuatunya lebih baik dari yang lain.."],
  ["CL","Memastikan tidak ada penyimpangan dalam pekerjaan."],
  ["PL","Menyiapkan rencana detail termasuk resiko kegagalannya."],
  ["CR","Mendiskusikan ide-ide baru."],
  ["AT","Menganalisa beragam hal sampai detail."],
  ["CT","Membuat kesimpulan dari beragam informasi."],
  ["ST","Mendiskusikan strategi jangka panjang."],
  ["OR","Mengelola kelebihan dan kekurangan sumberdaya saat bekerja."],
  ["AC","Bekerja dalam suasana yang kompetitif."],
  ["PL","Merencanakan langkah kerja sesuai dengan waktu dan sumberdaya."],
  ["CR","Mengembangkan metode baru dalam rangka efisiensi kerja."],
  ["AT","Mendalami suatu topik serinci mungkin."],
  ["CT","Menelaah hal-hal yang bersifat konseptual."],
  ["ST","Memproyeksikan keadaan sekarang ke masa depan."],
  ["OR","Memastikan sumberdaya teralokasi secara efektif dan efisien."],
  ["SA","Memahami sudut pandang orang lain."],
  ["AC","Memiliki dorongan kuat untuk mencapai tujuan."],
  ["CR","Mempraktekkan cara yang baru pada pekerjaan yang rutin."],
  ["AT","Mengerjakan hal-hal detail."],
  ["CT","Menyimpulkan hasil sebuah proses diskusi."],
  ["ST","Mengantisipasi kendala yang akan muncul di masa mendatang."],
  ["OR","Mengorganisir pelaksanaan beragam proyek supaya tidak tumpang tindih."],
  ["SA","Menangkap situasi emosi orang lain."],
  ["NT","Mengembangkan jejaring/hubungan sosial seluas mungkin."],
  ["AC","Menetapkan sasaran yang menantang."],
  ["AT","Mengurai masalah hingga ke akar permasalahan."],
  ["CT","Mengenalkan wacana baru untuk suatu kegiatan yang rutin."],
  ["ST","Membuat simulasi jangka panjang."],
  ["OR","Memastikan kesesuaian alokasi sumberdaya dengan prioritas kerja."],
  ["SA","Mengenali kondisi emosi orang lain."],
  ["NT","Memupuk dan mengelola jejaring/hubungan sosial yang erat."],
  ["PS","Bernegosiasi dalam rangka pendapat pribadi dapat diterima."],
  ["AC","Bersemangat menghadapi pekerjaan yang menantang."],
  ["CT","Membandingkan teori dengan kenyataan."],
  ["ST","Menganalisa kemungkinan yang bisa terjadi di masa depan."],
  ["OR","Mengarahkan sumber daya untuk mencapai target."],
  ["SA","Memperhatikan pengaruh emosi pada kinerja."],
  ["NT","Membina dan mengembangkan hubungan yang saling menguntungkan."],
  ["PS","Memakai beragam pendekatan supaya pendapat pribadi diterima."],
  ["AD","Mencermati perubahan dan menelaah kendala-kendalanya."],
  ["AC","Mengerjakan segala sesuatunya lebih baik dari yang lain."],
  // [null, null] // HACK
]